INSERT INTO PUBLIC.ADDRESS (STREET, CITY, POSTAL_CODE) VALUES ('Nalkowskiej 4B', 'Ruda Slaska', '41-700');
INSERT INTO PUBLIC.ADDRESS (STREET, CITY, POSTAL_CODE) VALUES ('Nałkowskiej 4B m. 23', 'Ruda Śląska', '41-700');
INSERT INTO PUBLIC.APP_USER (FIRST_NAME, LAST_NAME, ADDRESS_ID) VALUES ('John', 'Doe', 1);
INSERT INTO PUBLIC.APP_USER (FIRST_NAME, LAST_NAME, ADDRESS_ID) VALUES ('Joan', 'Doe', 2);